version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: ghostikgh/golang-bot
    environment:
      CREATE_TABLE: 'yes'
      DB_SWITCH: 'on'
      TOKEN: 6201240293:AAHdMaz4Qu8ShdCfCQSFskqWGe1-bxw1-uU
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
